version: '3'

services:
  messageprocessor:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

  admin:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"


  screen:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"

