version: '3'

services:
  admin:
    image: admin:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_admin$
    volumes:
      - C:\Users\Kennie\Desktop\VS\MessageProcessor\MessageProcessor\Admin:/app
      - C:\Users\Kennie\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_admin$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_admin$ bin/Debug/netcoreapp2.0/Admin.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

  api:
    image: api:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_api$
    volumes:
      - C:\Users\Kennie\Desktop\VS\MessageProcessor\MessageProcessor\api:/app
      - C:\Users\Kennie\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_api$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_api$ bin/Debug/netcoreapp2.0/api.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""


  messageprocessor:
    image: messageprocessor:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_messageprocessor$
    volumes:
      - C:\Users\Kennie\Desktop\VS\MessageProcessor\MessageProcessor\MessageProcessor:/app
      - C:\Users\Kennie\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_messageprocessor$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_messageprocessor$ bin/Debug/netcoreapp2.0/MessageProcessor.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""


  screen:
    image: screen:dev
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      #- NUGET_FALLBACK_PACKAGES=$container_paths_to_fallback_packages_screen$
    volumes:
      - C:\Users\Kennie\Desktop\VS\MessageProcessor\MessageProcessor\Screen:/app
      - C:\Users\Kennie\vsdbg\vs2017u5:/remote_debugger:ro
#$nuget_volume_mapping_screen$
    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      #com.microsoft.visualstudio.debuggee.arguments: " $debuggee_arguments_probing_paths_screen$ bin/Debug/netcoreapp2.0/Screen.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/bash -c \"if PID=$$(pidof -x dotnet); then kill $$PID; fi\""

